import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'
import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Joel Aduma Developer DogTag</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={styles.main}>
              
                {children}
            </main>

<Footer/>
        </div>
    )
}

export default Layout